'use client';

import './globals.css'
import { Inter } from 'next/font/google'
import NextLink from 'next/link'
import { ColorModeScript } from '@chakra-ui/react'

import { AppShell }from '@saas-ui/react';
import {Sidebar, SidebarSection, NavItem, SaasUILogo} from '@saas-ui/sidebar';
import { SaasProvider, LinkProps } from '@saas-ui/react'
import { Box } from '@chakra-ui/react';
import { userContext as UserContext } from '@/components/UserContext';
import { StarIcon } from '@chakra-ui/icons';


const inter = Inter({ subsets: ['latin'] })

const Link = (props) => {
  return <NextLink {...props} legacyBehavior />
}
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SaasProvider linkComponent={Link}>
        <AppShell
                navbar={
                  <Box as="header" borderBottomWidth="1px" py="2" px="4">
                    <StarIcon />
                  </Box>
                }
                sidebar={
                  <Sidebar>
                    <SidebarSection>
                      <NavItem href='/'>Home</NavItem>
                      <NavItem href='/new-user'>New User</NavItem>
                      <NavItem href='/list-users'>List Users</NavItem>
                    </SidebarSection>
                  </Sidebar>
                }
            >
              <UserContext.Provider value={{users:[]}}>
              {children}
            </UserContext.Provider>
          </AppShell>
          </SaasProvider>
      </body>
    </html>
  )
}
